version: "3.9"

services:
  jupyter:
    image: mlops-train:latest  # replace with your custom image name if built
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/Content_Moderation_System/Model Training:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: >
       bash -c "python3 -m pip install torch pandas mlflow && start-notebook.sh"
