name: jigsaw-etl

volumes:
  jigsaw_data:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - jigsaw_data:/data
      - ./kaggle.json:/root/.kaggle/kaggle.json:ro
    working_dir: /data
    environment:
      - KAGGLE_CONFIG_DIR=/root/.kaggle
    command:
      - bash
      - -c
      - |
        set -e

        echo "Installing dependencies..."
        pip install kaggle unzip

        echo "Resetting Jigsaw directory..."
        rm -rf Jigsaw
        mkdir -p Jigsaw
        cd Jigsaw

        echo "Downloading dataset from Kaggle..."
        kaggle competitions download -c jigsaw-unintended-bias-in-toxicity-classification

        echo "Unzipping dataset..."
        unzip -q train.csv.zip
        unzip -q test.csv.zip
        rm -f *.zip

        echo "Final contents of /data/Jigsaw:"
        ls -lh

  transform-data:
    container_name: etl_transform_data
    image: python:3.11
    volumes:
      - jigsaw_data:/data
      - ../scripts/split_by_timestamp.py:/data/Jigsaw/split_by_timestamp.py:ro
    working_dir: /data/Jigsaw
    command:
      - bash
      - -c
      - |
        set -e
        pip install pandas scikit-learn

        echo "Running timestamp-based split script..."
        python3 split_by_timestamp.py

        echo "Done splitting. Final files:"
        ls -l

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - jigsaw_data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Uploading to object storage bucket: $RCLONE_CONTAINER"
        rclone copy /data/Jigsaw chi_uc:$RCLONE_CONTAINER \
        --progress --transfers=16 --checkers=8 \
        --multi-thread-streams=4 --fast-list

        echo "Files in bucket:"
        rclone lsf chi_uc:$RCLONE_CONTAINER
