replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/content-moderation-system
  tag: canary-1.0.0

service:
  port: 8080
  externalIP: ""

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"
